### ISSUE TITLE
We encountered an error!

### ISSUE THREAD

**Issue by MidgeMouse** [leslie-alldridge/xero-bulk-void-invoice-tool#5]
Hi,

I have been using the bulk invoice tool and it has been working pretty well (only 5 - 10 invoices per month need to be deleted by hand), thanks for your hard work on creating this much need tool (I have almost 13k invoices to delete).

I now can't connect and keep getting this error. 

We encountered an error!
Please click below to reload the main page. It's likely your API key expired or the connection to your organisation was lost. We may have loaded old credentials so be sure to use the "Disconnect from Xero" button at the end of each session.

Any help would be really appreciated.

Many thanks,
Midge

**Comment by MidgeMouse** [comment]
Seems to be working again :)

**Comment by leslie-alldridge** [comment]
@MidgeMouse glad it's working for you :) - I don't store any credentials at all (mostly to keep myself + the users safe) so it's likely that during your web browser session the 30 minute token expired. In those events, it's best to refresh and try again. Whilst it's definitely possible to add better token handling...it's safest for me to not do so especially since accounting is such sensitive information.
